language: node_js
node_js:
  - "6"
  - "4"
script: npm test -- --coverage
after_script:
  ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info
addons:
    code_climate:
        repo_token: ed88a16c3f6f87bd4300e62f4fffd607667b98b5a7d7c8cea8a25b4a409316d5
